### ISSUE TITLE
真的会有人从浏览器里直接调用 OTS 吗

### ISSUE THREAD

**Issue by JacksonTian** [aliyun/aliyun-tablestore-nodejs-sdk#1]
看到 兼容浏览器的 XHR，比较疑问。

**Comment by boxiaowpl** [comment]
没有用户直接从浏览器调用OTS，有这种兼容写法主要是因为很多代码从其他框架挪过来的，像事件机制其实也是兼容写法，后面还是会考虑进行修改。
