### ISSUE TITLE
为何getRow时必须传入主键

### ISSUE THREAD

**Issue by beary** [aliyun/aliyun-tablestore-nodejs-sdk#17]
一个常见场景：
用户通过手机号注册时，需要检查该手机号是否注册过。如果必须传入主键(id)那岂不是无法查询。

当然，可以把手机号也设置为主键，但是这样就无法解绑/修改手机号了。

还是说表格存储并不适用于这样的场景。

**Comment by boxiaowpl** [comment]
最好的方式是把手机号设置为第一主键，解绑/修改手机号只需要删除后重新插入即可。

**Comment by beary** [comment]
@boxiaowpl 谢谢，想了下这个方式确实很合理
