### ISSUE TITLE
Get Row Always Empty

### ISSUE THREAD

**Issue by sukianto** [aliyun/aliyun-tablestore-nodejs-sdk#38]
I have a problem for GetRow I have these params:
const params = {
      tableName: 'table_name',
      primaryKey: [
        { 'gid': 'something' },
        { 'uid': 'something' }
      ],
      maxVersions: 1,
      columnsToGet: ['username', 'address']
    }
gid is the partition key
uid is the primary key

const queryResult = await client.getRow(params).then(data => {
      return data
    }).catch(err => {
      throw err
    })

I do this in function compute environment
I'm sure my syntax is correct, but the returned row is always empty

{
        "consumed": {
            "capacityUnit": {
                "read": 1,
                "write": 0
            }
        },
        "row": ""
}

Do I need to open permission for the related access and secret key?
I already open OTS full access

**Comment by grapewheel** [comment]
@sukianto  I also get the same problem, how did you solve it??
