### ISSUE TITLE
[bug]v5.1.0 “10_000” for numbers casing a SyntaxError

### ISSUE THREAD

**Issue by gemwuu** [aliyun/aliyun-tablestore-nodejs-sdk#53]
![image](https://user-images.githubusercontent.com/4635838/155515971-6efaf0f8-d996-476f-a724-cb706b377aa9.png)

**Comment by wangtantan** [comment]
10_000 can't be recognized lower than node 12，5.1.1 has been published  to fix it.

**Comment by fengmk2** [comment]
https://github.com/aliyun/aliyun-tablestore-nodejs-sdk/commit/4f204820d29a4f5ff1abeff1972f36ba4b2c771d 已经修复
