### ISSUE TITLE
项目中使用了已弃用的web标准属性：__proto__,请修改一下以便兼容新的js runtime deno

### ISSUE THREAD

**Issue by Tyrone** [aliyun/aliyun-tablestore-nodejs-sdk#60]
lib/client.js
 var buffer = request.__proto__.constructor.encode(request);
 修改为：
 var buffer =  Object.getPrototypeOf(request).constructor.encode(request);

 lib/protocol/encoder.js
 const writer = aggBody.__proto__.constructor.encode(aggBody);
 修改为：
 const writer = Object.getPrototypeOf(aggBody).constructor.encode(aggBody);

**Comment by xjtushilei** [comment]
2天内发布5.3.1版本，修改这个问题
