### ISSUE TITLE
Checksum mismatch

### ISSUE THREAD

**Issue by shang309073819** [aliyun/aliyun-tablestore-nodejs-sdk#9]
const params = {
		tableName: "fenfa_news",
		primaryKey: [{ 'pk1_news_id':'000197384a0513cd474e5bcc18fbc105'}],
	};
	client.getRow(params, (err, data) => {
		if (err) {
			console.log('error:', err);
			return;
		}
		console.log(data)
		return res.json({data: data});
	});

Checksum mismatch？

**Comment by boxiaowpl** [comment]
fixed, sorry for the mistake.
